language: go

go:
  - 1.8.x
  - 1.9.x
  - master

matrix:
  allow_failures:
    - go: master
  fast_finish: true

# To avoid any failure
before_install:
  - mkdir -p ~/.tfversion/{tmp,bin}

script:
  - make test
  - make vet

notifications:
  email:
    recipients:
    - a.perrier89@gmail.com
    on_success: change
    on_failure: always